### ISSUE TITLE
Mac installation issue

### ISSUE THREAD

**Issue by den-vasyliev** [ibayro/devsecops#1]
Hi, could you please check for errors on my Mac during the git commit:

 `gitleaks not found. Installation gitleaks.
----------------------------------
gitleaks: Can't create 'gitleaks'
tar: Error exit delayed from previous errors.
gitleaks installed
.git/hooks/pre-commit: line 93: gitleaks: command not found
----------------------------------
Secrets found in the code. Commit rejected.
----------------------------------`

**Comment by ibayro** [comment]
Hello @den-vasyliev 
I have made a possible fix, could you please check, verify and comment? 
Thanks

**Comment by den-vasyliev** [comment]
Now works for me - thanks!
Cloud you please add `git config hooks.gitleaks-enable true` in documentation.
If not enabled, the hook will not work until manually triggered

**Comment by ibayro** [comment]
@den-vasyliev 
Great, glad that it works.
And thank you very much for pointing out a step for a hook, I should have done it in the first place :)
Best regards,
Ihor
